spring:
  application:
    name: email-reader
  config:
    import: "optional:file:.env[.properties]"

email:
  host:            ${EMAIL_HOST}
  username:        ${EMAIL_USERNAME}
  password:        ${EMAIL_PASSWORD}
  protocol:        ${EMAIL_PROTOCOL}
  check-interval:  ${EMAIL_CHECK_INTERVAL:60}
